notifications:
  email:
  - cf-lamb@pivotallabs.com
env:
  global:
  - secure: ! 'jAPpeCpKZrRdVrexHONGy1YUksbb7WYMvYLGKbcatvRXW7pw/l77uGvg+93e

      EAuriBUhEVMCnnapnRumNbLnPY0+QQ3Hrw3cMDjkgYunC5nI/tI3EZ2x31HP

      /fP/9PHF4sW5Kv45aVKr/N8zJ6yrcj+d4imasLPKe6GAc/5493Q='
  - secure: ! 'WS9xUNmBou6daEIKu4PRLDlb9rMZlr+QRtkLPjm5M4vQD3FQEBlETv7Em4Z1

      k9QIM3Yx9qeZRy+9WpFGs+1XG/foo4LUdt/epu2P2pFCA1PzA8Ib9xI7EZSp

      y0FoJxVHyWVueS/mQzil+Ihk1TJUUibWRPzxo+t/8cNX+ogmse4='
  - secure: D7ypvdD4ArKKdbrIMM7EUITNVjZlTH6ASwO+9qsL0g+qT66Z4kn4iiqMHi+V7ujglCZqQYNBrRRCqYQDLhCjFOUTRlIEgPJtR3uXdWgXfJ15Wm3I0R8tmeQMNOjgM+nAnXNnA+Feh8jIWqlvrJ1tg7S8q4rJGmJhfxpsnRlHf6o=
  - secure: ZZLGcFUKd2hc4fkuLvbTiPhwejctQAmSF3ICxZ6UxSrjcppiUtwLSaucAoki0l0+hiRFUNQO/+rFZMo0qDCsspZ9dTm2QtSFPotdP9/zYVNSp91/EXNmQ6VR9vcubTiJa5JPGoe9d4+Z7W4MY8upfs2fMNyv+7uq+GEvWhm3kj4=
  - secure: GGNK3EdRGczAeow8u6/UuS3qg6tgGfHfoinzM8Vxmo2ik1bKJHZYLR9JpYILtj0+dv/Hz8ZPDvH1Htci8ZaIZTsU2CL8XeTKQCVdNfSGLOKqcC4+eBTmoFVp//GtRrTW7LGQOFhaN9I41bFWdAxYcQsc6wCUGeJvFZStQW0ebmQ=
  - secure: bym27gH1hvr2eOk5oeH8mVQToiIpu1hhmC8xmGrJyBnzWcJk3R8FLpHFQSm+XQowVJSnuYIe/G4MPTEggLrIfj/wADEkFGMhsv1hhYV2Sa0psBizZp7Pdy05lHdiLQEh8VnjRUSMfBTAkl8JmZdzvEe9W0dgdhSWM53Ed6TId54=

language: go

go:
- 1.2.1

before_install:
- export WORK_DIR=`pwd`
- export GOPATH=$WORK_DIR
- go get -v code.google.com/p/go.tools/cmd/vet
- go get -v code.google.com/p/go.tools/cmd/cover
- go get -v github.com/mattn/goveralls
- go get -v github.com/onsi/ginkgo
- go get -v github.com/onsi/gomega
- go get -v github.com/apcera/nats
- go install -v github.com/onsi/ginkgo/ginkgo
- git submodule update --init --recursive

install: echo "Build later"

script: PATH=$HOME/gopath/bin:$PATH ./bin/test

after_success:
- 'echo "mode: set" > all.coverprofile'
- 'find . -name "*.coverprofile" -exec grep -v mode: {} >> all.coverprofile \;'
- $WORK_DIR/bin/goveralls -coverprofile=all.coverprofile -repotoken=$COVERALLS_TOKEN
