name: loggregator

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: loggregator
  version: latest
- name: bosh-dns
  version: 0.0.11

addons:
- name: bosh-dns
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      aliases:
        doppler.service.cf.internal:
        - '*.doppler.default.cf.bosh'
        loggregator-trafficcontroller.service.cf.internal:
        - '*.log-api.default.cf.bosh'
        reverse-log-proxy.service.cf.internal:
        - '*.log-api.default.cf.bosh'

instance_groups:
- name: loggregator-acceptance-tests
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  lifecycle: errand
  networks:
  - name: default
  jobs:
  - name: loggregator-acceptance-tests
    release: loggregator
    properties:
      traffic_controller:
        disable_access_control: true
  - name: metron_agent
    release: loggregator
    properties: &metron_agent_properties
      doppler:
        addr: doppler.service.cf.internal
      metron_agent:
        disable_udp: false
        deployment: loggregator
        bosh_dns: true
      loggregator:
        tls:
          ca_cert: "((loggregator_metron.ca))"
          metron:
            cert: "((loggregator_metron.certificate))"
            key: "((loggregator_metron.private_key))"

- name: doppler
  azs:
  - z1
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: doppler
    release: loggregator
    properties:
      doppler:
        disable_announce: true
        syslog_skip_cert_verify: true
      loggregator:
        disable_syslog_drains: true
        tls:
          ca_cert: "((loggregator_doppler.ca))"
          doppler:
            cert: "((loggregator_doppler.certificate))"
            key: "((loggregator_doppler.private_key))"
  - name: metron_agent
    release: loggregator
    properties: *metron_agent_properties

- name: log-api
  azs:
  - z1
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: loggregator_trafficcontroller
    release: loggregator
    properties:
      cc:
        internal_service_hostname: ""
        tls_port: 0
        mutual_tls:
          ca_cert: "((loggregator_tc.ca))"
      uaa:
        url: ""
      system_domain: unused
      traffic_controller:
        disable_access_control: true
      loggregator:
        tls:
          ca_cert: "((loggregator_tc.ca))"
          trafficcontroller:
            cert: "((loggregator_tc.certificate))"
            key: "((loggregator_tc.private_key))"
          cc_trafficcontroller:
            cert: "((loggregator_tc.certificate))"
            key: "((loggregator_tc.private_key))"
        uaa:
          client_secret: "some-secret"
      ssl:
        skip_cert_verify: false
  - name: metron_agent
    release: loggregator
    properties: *metron_agent_properties
  update:
    max_in_flight: 1
    serial: true

- name: reverse_log_proxy
  azs:
  - z1
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: reverse_log_proxy
    release: loggregator
    provides:
      reverse_log_proxy: {as: reverse_log_proxy, shared: true}
    properties:
      loggregator:
        tls:
          ca_cert: "((loggregator_rlp.ca))"
          reverse_log_proxy:
            cert: "((loggregator_rlp.certificate))"
            key: "((loggregator_rlp.private_key))"
  - name: metron_agent
    release: loggregator
    properties: *metron_agent_properties
  update:
    max_in_flight: 1
    serial: true

variables:
- name: loggregator_ca
  type: certificate
  options:
    common_name: loggregatorCA
    is_ca: true
- name: loggregator_doppler
  type: certificate
  options:
    ca: loggregator_ca
    common_name: doppler
    extended_key_usage:
    - client_auth
    - server_auth
- name: loggregator_tc
  type: certificate
  options:
    ca: loggregator_ca
    common_name: trafficcontroller
    extended_key_usage:
    - client_auth
    - server_auth
- name: loggregator_rlp
  type: certificate
  options:
    ca: loggregator_ca
    common_name: reverselogproxy
    extended_key_usage:
    - client_auth
    - server_auth
- name: loggregator_metron
  type: certificate
  options:
    ca: loggregator_ca
    common_name: metron
    extended_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
