golang-1.25-linux/8cbbeb9a25df0cd15038235e0504a02ae6a1badd0b923d46d99a9db1654704a9:
  size: 59660846
  object_id: 5ebfcba6-1b10-4eec-5bc0-b7a48c34dd20
  sha: sha256:7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e
golang-1.25-linux/18d8a51c097f1b3957720a705fd2d00e8062e50cfe48ad1ac3e06b8bf234d5ee:
  size: 59768749
  object_id: 2b5b5fb1-4b52-42bd-5916-29f7f067ec9e
  sha: sha256:12e6d6a191091ae27dc31f6efc630e3a3b8ba409baf3573d955b196fdf086005
golang-1.25-windows/117efdd98cac4d6d362504cddfb6e0926852569d5dd7330479e26c5477b5ada0:
  size: 67448678
  object_id: 5251b369-ab7a-455e-5479-6ed97722d9fa
  sha: sha256:c75e5f4ff62d085cc0017be3ad19d5536f46825fa05db06ec468941f847e3228
golang-1.25-windows/976ff3d53aec4af1244ca8b2ab0be7ffd977dafd6dd805771df8508cb4998087:
  size: 67442664
  object_id: ccfd02ec-3b0c-49e8-686f-09b3c207e397
  sha: sha256:ae756cce1cb80c819b4fe01b0353807178f532211b47f72d7fa77949de054ebb
golang-1.25-windows/924223df4c326000999e7554ab10919d80de3df3483a2eb60d0494771a9e073c:
  size: 67446385
  object_id: 017b0170-2457-497b-4a31-3871fd166df4
  sha: sha256:19b4733b727ba5c611b5656187f3ac367d278d64c3d4199a845e39c0fdac5335
golang-1.25-windows/b59a156693e6667d9a6f981dce2dc2a268d292bd94fa0ddb4fa4b756f535bbef:
  size: 67439680
  object_id: 92edeb52-8daf-40fa-54e1-3a3f3c387382
  sha: sha256:bc249a599c6fe9d0d4093c363856f6c6320dbbe05e5d5d8818b711fb4a14fc23
golang-1.25-windows/fdc6f89451567c145ae473d9dee3b4828cb3c741829125604e98d8e37bbfe51f:
  size: 67419304
  object_id: c5a5190b-424e-4374-7e07-606157d00af3
  sha: sha256:4a974de310e7ee1d523d2fcedb114ba5fa75408c98eb3652023e55ccf3fa7cab
