golang-1.25-linux/8cbbeb9a25df0cd15038235e0504a02ae6a1badd0b923d46d99a9db1654704a9:
  size: 59660846
  object_id: 5ebfcba6-1b10-4eec-5bc0-b7a48c34dd20
  sha: sha256:7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e
golang-1.25-linux/18d8a51c097f1b3957720a705fd2d00e8062e50cfe48ad1ac3e06b8bf234d5ee:
  size: 59768880
  object_id: d51f1b56-2904-4cda-7d35-2ac0359955b8
  sha: sha256:f022b6aad78e362bcba9b0b94d09ad58c5a70c6ba3b7582905fababf5fe0181a
golang-1.25-windows/976ff3d53aec4af1244ca8b2ab0be7ffd977dafd6dd805771df8508cb4998087:
  size: 67442664
  object_id: ccfd02ec-3b0c-49e8-686f-09b3c207e397
  sha: sha256:ae756cce1cb80c819b4fe01b0353807178f532211b47f72d7fa77949de054ebb
golang-1.25-windows/924223df4c326000999e7554ab10919d80de3df3483a2eb60d0494771a9e073c:
  size: 67446385
  object_id: 943263d0-0828-4426-67ff-d8a2d95fd60d
  sha: sha256:19b4733b727ba5c611b5656187f3ac367d278d64c3d4199a845e39c0fdac5335
golang-1.25-windows/b59a156693e6667d9a6f981dce2dc2a268d292bd94fa0ddb4fa4b756f535bbef:
  size: 67439680
  object_id: 92edeb52-8daf-40fa-54e1-3a3f3c387382
  sha: sha256:bc249a599c6fe9d0d4093c363856f6c6320dbbe05e5d5d8818b711fb4a14fc23
golang-1.25-windows/fdc6f89451567c145ae473d9dee3b4828cb3c741829125604e98d8e37bbfe51f:
  size: 67419304
  object_id: c5a5190b-424e-4374-7e07-606157d00af3
  sha: sha256:4a974de310e7ee1d523d2fcedb114ba5fa75408c98eb3652023e55ccf3fa7cab
