name: pull-request-ci
on:
  pull_request:
    branches:
    - main
    - v105.6.x
    - v106.3.x
  push:
    branches:
    - main
    - v105.6.x
    - v106.3.x
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go test -v -race ./...
        working-directory: src
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go vet ./...
        working-directory: src
